# Advent of code 2021

In [ ]:
pip install aocd

In [1]:
### imports

from aocd import submit
from aocd.models import Puzzle
import typing as tp
import os
import numpy as np
import re
import math

os.environ["AOC_SESSION"]="53616c7465645f5f6d9daabe7926fe3860734a70143382fbf0871c7206c1f5a9c1ed3158b28de5d90b71fc296387cb5b"

### Day 25

In [ ]:
puzzle=Puzzle(year=2021,day=25)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 24

In [ ]:
puzzle=Puzzle(year=2021,day=24)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 23

In [ ]:
puzzle=Puzzle(year=2021,day=23)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 22

In [ ]:
puzzle=Puzzle(year=2021,day=22)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 21

In [ ]:
puzzle=Puzzle(year=2021,day=21)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 20

In [ ]:
puzzle=Puzzle(year=2021,day=20)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 19

In [ ]:
puzzle=Puzzle(year=2021,day=19)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
submit(answer=ans_b,day=3,part="b",year=2021)

### Day 18

In [ ]:
puzzle=Puzzle(year=2021,day=18)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 17

In [ ]:
puzzle=Puzzle(year=2021,day=17)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 16

In [ ]:
puzzle=Puzzle(year=2021,day=16)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
submit(answer=ans_b,day=3,part="b",year=2021)

### Day 15

In [ ]:
puzzle=Puzzle(year=2021,day=15)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 14

In [ ]:
puzzle=Puzzle(year=2021,day=14)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 13

In [ ]:
puzzle=Puzzle(year=2021,day=13)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 12

In [ ]:
puzzle=Puzzle(year=2021,day=12)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 11

In [ ]:
puzzle=Puzzle(year=2021,day=11)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 10

In [ ]:
puzzle=Puzzle(year=2021,day=10)
print(puzzle.easter_eggs)


#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 9

In [2]:
puzzle=Puzzle(year=2021,day=9)

#### Part a

In [7]:
class Coordinate:
    def __init__(self,x:int,y:int) -> None:
        self.x=x
        self.y=y
    
    def __eq__(self,other)->bool:
        return self.x==other.x and self.y==other.y


def find_low_points(grid:np.array)->tp.List[Coordinate]:
    return_list=[]
    for id_x in range(len(grid)):
        for id_y in range(len(grid[0])):
            
            not_to_check=[]
            if id_x==0:
                not_to_check.append("idx_bot")
            if id_x==len(grid)-1:
                not_to_check.append("idx_top")
            if id_y==0:
                not_to_check.append("idy_bot")
            if id_y==len(grid[0])-1:
                not_to_check.append("idy_top")
            
            if ("idx_bot" in not_to_check or grid[max(id_x-1,0),id_y] > grid[id_x,id_y]) \
                and ("idx_top" in not_to_check or grid[id_x,id_y] < grid[min(id_x+1,len(grid)-1),id_y]) \
                and ("idy_bot" in not_to_check or grid[id_x,max(id_y-1,0)] > grid[id_x,id_y]) \
                and ("idy_top" in not_to_check or grid[id_x,id_y] < grid[id_x,min(id_y+1,len(grid[0])-1)] ):
                    return_list.append(Coordinate(id_x,id_y))
    return return_list
grid=np.array([list(map(int,[character for character in line])) for line in puzzle.input_data.split("\n")])
#grid=np.array([list(map(int,[character for character in line])) for line in open("example_day9.txt").read().split("\n")])

low_points=find_low_points(grid)
ans_a=sum(grid[coor.x,coor.y] for coor in low_points)+len(low_points)
print(ans_a)

print(puzzle.easter_eggs)


572
[<span title="This was originally going to be a puzzle about watersheds, but we're already under water.">settles like rain</span>]


In [4]:
puzzle.answer_a = ans_a

Part a already solved with same answer: 572


#### Part b

In [5]:
def find_higher_neighbours(grid:np.array,coor:Coordinate)->tp.List[Coordinate]:
    return_list=[]
    if coor.x!=0 and 9 > grid[coor.x-1,coor.y]>grid[coor.x,coor.y]:
        return_list.append(Coordinate(coor.x-1,coor.y))
    if coor.x!=len(grid)-1 and 9 > grid[coor.x+1,coor.y]>grid[coor.x,coor.y]:
        return_list.append(Coordinate(coor.x+1,coor.y))
    if coor.y!=0 and 9 > grid[coor.x,coor.y-1]>grid[coor.x,coor.y]:
        return_list.append(Coordinate(coor.x,coor.y-1))
    if coor.y!=len(grid[0])-1 and 9 > grid[coor.x,coor.y+1]>grid[coor.x,coor.y]:
        return_list.append(Coordinate(coor.x,coor.y+1))
    return return_list


bassins=[[coor] for coor in low_points]

for i_bassin,low_point in enumerate(low_points):
    coords_to_check=[low_point]
    while len(coords_to_check)!=0:
        new_coords=[coor for coor in find_higher_neighbours(grid,coords_to_check[0]) if not coor in bassins[i_bassin]]
        bassins[i_bassin]+=new_coords
        coords_to_check=coords_to_check[1:]+new_coords

bassins=sorted(bassins,key=len)

ans_b=math.prod(list(map(len,bassins[-3:])))

print(ans_b)

847044


In [6]:
puzzle.answer_b = ans_b

### Day 8

In [8]:
puzzle=Puzzle(year=2021,day=8)
print(puzzle.easter_eggs)


[<span title="Yes, just the four-digit seven-segment ones. Whole batch must have been faulty.">they must have been damaged</span>]


#### Part a

In [4]:
reads=puzzle.input_data.split('\n')

ctr_a=0

for line in reads:
    numbers=line.split(" | ")[1].split(" ")
    ctr_a+=len([val for val in numbers if len(val)<=4 or len(val)==7])

ans_a=ctr_a
print(ans_a)

495


In [5]:
puzzle.answer_a = ans_a

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


#### Part b

In [61]:
def is_in_other_number(number1:str,number2:str)->bool:
    return all([character in number2 for character in number1])

def fill_dict(options:tp.List[str])->dict:
    encoder={}
    encoder[1]=[val for val in options if len(val)==2][0]
    encoder[4]=[val for val in options if len(val)==4][0]
    encoder[7]=[val for val in options if len(val)==3][0]
    encoder[8]=[val for val in options if len(val)==7][0]
    encoder[3]=[val for val in options if len(val)==5 and is_in_other_number(encoder[1],val)][0]
    encoder[2]=[val for val in options if len(val)==5 and not is_in_other_number(encoder[1],val) and
               not is_in_other_number("".join([character for character in encoder[4] if not character in encoder[1]]),val)][0]
    encoder[5]=[val for val in options if len(val)==5 and not is_in_other_number(encoder[1],val) and
               is_in_other_number("".join([character for character in encoder[4] if not character in encoder[1]]),val)][0]
    encoder[0]=[val for val in options if len(val)==6 and not is_in_other_number(encoder[5],val)][0]
    encoder[6]=[val for val in options if len(val)==6 and is_in_other_number(encoder[5],val) and not is_in_other_number(encoder[1],val)][0]
    encoder[9]=[val for val in options if len(val)==6 and is_in_other_number(encoder[5],val) and is_in_other_number(encoder[1],val)][0]
    return encoder

def invert_dictionary(encoder:dict)->dict:
    wiring={}
    for val in encoder:
        wiring[encoder[val]]=val
    return wiring

ctr_b=0
for line in reads:
    [examples,number_encoded]=line.split(" | ")
    encoder=fill_dict(list(map(lambda x: "".join(sorted(x)),examples.split(" "))))
    wiring=invert_dictionary(encoder)
    number=[wiring["".join(sorted(val))] for val in number_encoded.split(" ")]
    number=int("".join([str(val) for val in number]))
    ctr_b+=number

ans_b=ctr_b
print(ans_b)


1055164


In [62]:
puzzle.answer_b = ans_b

### Day 7

In [10]:
puzzle=Puzzle(year=2021,day=7)
print(puzzle.easter_eggs)


[<span title="This appears to be due to the modial interaction of magneto-reluctance and capacitive duractance.">don't burn fuel at a constant rate</span>]


#### Part a

In [80]:
crabs=list(map(int,puzzle.input_data.split(",")))

def calc_fuel(crabs:tp.List[int],target:int,power=1):
    if power==1:
        return sum(abs(pos-target) for pos in crabs)
    if power==2:
        distances=[abs(pos-target) for pos in crabs]
        return sum(pos*(pos+1)/2 for pos in distances)
from statistics import median

best_pos=0
best_fuel=10000000000

#for pos in range(max(crabs)):
#    new_fuel=calc_fuel(crabs,pos)
#    if new_fuel<best_fuel:
#        best_fuel=new_fuel
#        best_pos=pos

best_pos_a=int(median(crabs))

print(best_pos_a)
ans_a=calc_fuel(crabs,best_pos_a)
print(ans_a)

362
355150


In [75]:
puzzle.answer_a = ans_a

#### Part b

In [83]:
best_pos_b=sum(crabs)/len(crabs)


ans_b=int(min(calc_fuel(crabs,int(best_pos_b),2),calc_fuel(crabs,int(best_pos_b+1),2)))
print(best_pos_b,ans_b)


499.568 98368490


In [84]:
puzzle.answer_b = ans_b

### Day 6

In [11]:
puzzle=Puzzle(year=2021,day=6)
print(puzzle.easter_eggs)


[<span title="I heard you like lanternfish.">each lanternfish creates a new lanternfish</span>]


#### Part a

In [7]:
from collections import Counter

input_population=[int(val) for val in puzzle.input_data.split(",")]
#input_population=[int(val) for val in "3,4,3,1,2".split(',')]

fish=Counter(input_population)

def one_generation(fish_pop:Counter)->Counter:
    new_pop=Counter()
    for age in range(8,0,-1):
        new_pop[age-1]=fish_pop[age]
    new_pop[6]+=fish_pop[0]
    new_pop[8]=fish_pop[0]
    return new_pop

target_a=80
for _ in range(target_a):
    fish=one_generation(fish)

ans_a=sum(fish.values())
print(ans_a)

395627


In [30]:
puzzle.answer_a = ans_a

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


#### Part b

In [8]:
target_b=256
fish=Counter(input_population)
for _ in range(target_b):
    fish=one_generation(fish)

ans_b=sum(fish.values())
print(ans_b)

1767323539209


In [34]:
puzzle.answer_b = ans_b

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 6! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


### Day 5

In [12]:
puzzle=Puzzle(year=2021,day=5)
print(puzzle.easter_eggs)


[<span title="Maybe they're Bresenham vents.">lines of vents</span>]


#### Part a

In [47]:
winds=[line.split(" -> ") for line in puzzle.input_data.strip().split('\n')]

    
class Coordinate:
    def __init__(self,x:int,y:int) -> None:
        self.x=x
        self.y=y
    
    def __eq__(self,other:Coordinate)->bool:
        return self.x==other.x and self.y==other.y


        
class Wind:
    def __init__(self,start_point:Coordinate,end_point:Coordinate) -> None:
        self.start_point=start_point
        self.end_point=end_point
        
    def get_coords(self) -> tp.List[Coordinate]:
        n_points=max(abs(self.start_point.x-self.end_point.x),abs(self.start_point.y-self.end_point.y))
        for n in range(n_points+1):
            if abs((self.start_point.x+n*(self.end_point.x-self.start_point.x)/(n_points))%1)>0.0000001:
                print("shit)")
            if abs((self.start_point.y+n*(self.end_point.y-self.start_point.y)/(n_points))%1>0.0000001):
                print("shit 2")
        return [Coordinate(int(self.start_point.x+n*(self.end_point.x-self.start_point.x)/(n_points)),
                     int(self.start_point.y+n*(self.end_point.y-self.start_point.y)/(n_points))) for n in range(n_points+1)]

    def is_straight(self) -> bool:
        if self.start_point.x==self.end_point.x or self.start_point.y==self.end_point.y:
            return True
        else:
            #print("no",self.start_point.x-self.end_point.x,self.start_point.y-self.end_point.y)
            return False


#winds=[line.split(" -> ") for line in open("example_day5.txt").read().strip().split('\n')]
#print(len(winds))
        
winds=[Wind(Coordinate(int(line[0].split(',')[0]),int(line[0].split(',')[1])),Coordinate(int(line[1].split(',')[0]),int(line[1].split(',')[1]))) for line in winds]     

#print(winds[8].start_point.x,winds[8].start_point.y,winds[8].end_point.x,winds[8].end_point.y,winds[8].is_straight())

grid=np.zeros((max([max(wind.start_point.y,wind.end_point.y) for wind in winds])+1,max([max(wind.start_point.x,wind.end_point.x) for wind in winds])+1))

test_wind1=Wind(Coordinate(0,35),Coordinate(0,13))
#print(test_wind1.is_straight())
ctr=0
#for coord in test_wind1.get_coords():
    #print(coord.x,coord.y)
    #ctr+=1

total_sum=0
for wind in winds:
    if wind.is_straight():
        total_sum+=(abs(wind.start_point.x-wind.end_point.x)+abs(wind.start_point.y-wind.end_point.y)+1)
        ctr+=1
        for coord in wind.get_coords():
            grid[coord.y,coord.x]+=1
#    else:
#        np.set_printoptions(threshold=sys.maxsize)
#        print(np.nonzero(grid))
#        print(wind.start_point.x,wind.start_point.y)
#        asadasd
print(ctr)


print(grid)
#print(sum(sum(grid)),total_sum)
ans_a=len([val for val in grid.flatten() if val>1])
print(ans_a)
#def find_intersect(wind1:wind,wind2:wind) -> [bool,tp.List[coord]]:
    

339
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
5774


In [4]:
puzzle.answer_a = ans_a

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


#### Part b

In [9]:
ctr=0
grid=np.zeros((max([max(wind.start_point.y,wind.end_point.y) for wind in winds])+1,max([max(wind.start_point.x,wind.end_point.x) for wind in winds])+1))
for wind in winds:
    total_sum+=(abs(wind.start_point.x-wind.end_point.x)+abs(wind.start_point.y-wind.end_point.y)+1)
    ctr+=1
    for coord in wind.get_coords():
        grid[coord.y,coord.x]+=1
ans_b=len([val for val in grid.flatten() if val>1])
print(ans_b)


18423


In [10]:
puzzle.answer_b = ans_b

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 5! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


### Day 4

In [13]:
puzzle=Puzzle(year=2021,day=4)
print(puzzle.easter_eggs)


[<span title="That's 'cuz a submarine don't pull things' antennas out of their sockets when they lose. Giant squid are known to do that.">let the giant squid win</span>]


#### Part a

In [ ]:
input_data=puzzle.input_data.split('\n\n')

drawn_numbers=[int(number) for number in input_data[0].split(',')]
boards=input_data[1:]

class bingo_board:
    def __init__(self,list_of_numbers:str) -> None:
        self.board_numbers=np.array([[int(number) for number in line.strip().split()] for line in list_of_numbers.split('\n')])
    
    def check_row(self,id_row:int,list_of_numbers:tp.List[int]):
        if all([number in list_of_numbers for number in self.board_numbers[id_row,:]]):
            return True
        else:
            return False
    def check_col(self,id_col:int,list_of_numbers:tp.List[int]):
        self.board_numbers=np.transpose(self.board_numbers)
        return_value=self.check_row(id_col,list_of_numbers)
        self.board_numbers=np.transpose(self.board_numbers)
        return return_value
    
    def check_win(self,list_of_numbers:tp.List[int]):
        if any([self.check_col(idx,list_of_numbers) or self.check_row(idx,list_of_numbers) for idx in range(len(self.board_numbers))]):
            return True
        else:
            return False

boards=[bingo_board(board) for board in boards]

def play_game_well(bingo_boards:tp.List[bingo_board],drawn_numbers:tp.List[int]):
    for n_drawn in range(len(bingo_boards[0].board_numbers),len(drawn_numbers)):
        for board in bingo_boards:
            if(board.check_win(drawn_numbers[:n_drawn])):
                return [board,n_drawn]


[board,n_drawn]=play_game_well(boards,drawn_numbers)
score=sum([number for number in  board.board_numbers.flat if not number in drawn_numbers[:n_drawn]])*drawn_numbers[n_drawn-1]
ans_a=score
print(score)

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
def play_game_badly(bingo_boards:tp.List[bingo_board],drawn_numbers:tp.List[int]):
    worst_n_drawn=0
    for id_board,board in enumerate(bingo_boards):
        [bad_board,n_win]=play_game_well([board],drawn_numbers)
        if n_win>worst_n_drawn:
            worst_n_drawn=n_win
            worst_board=bad_board
    return [worst_board,worst_n_drawn]

[board,n_drawn]=play_game_badly(boards,drawn_numbers)
score=sum([number for number in  board.board_numbers.flat if not number in drawn_numbers[:n_drawn]])*drawn_numbers[n_drawn-1]
ans_b=score
print(score)

In [ ]:
puzzle.answer_b = ans_b

### Day 3

In [14]:
puzzle=Puzzle(year=2021,day=3)
print(puzzle.easter_eggs)


[<span title="Turns out oceans are heavy.">odd creaking noises</span>]


#### Part a

In [ ]:
import timeit

diagnostics=puzzle.input_data.strip().split('\n')

def most_common(diagnostics: tp.List[str],position:int) -> str:
    all_bits=[diag[position] for diag in diagnostics]
    return max(sorted(set(all_bits),reverse=True), key = all_bits.count)

def least_common(diagnostics: tp.List[str],position:int) -> str:
    return str(1-int(most_common(diagnostics,position)))

gamma=""
for position in range(len(diagnostics[0])):
    gamma+=most_common(diagnostics,position)

gamma=int(gamma,2)


print(timeit.timeit(lambda: 2**(len(diagnostics[0]))-1-gamma,number=100000))
epsilon=2**(len(diagnostics[0]))-1-gamma

ans_a=gamma*epsilon
print(ans_a)

#### Nao's solution for timeit

In [ ]:
from collections import Counter
content = puzzle.input_data.split("\n")
def transpose(inlist: tp.Sequence[str]) -> tp.List[str]: 
    return ["".join(s) for s in zip(*inlist)]
def bin2int(binary: tp.Union[str, tp.Sequence[str]]) -> int: 
    if isinstance(binary, list): 
        return int("".join(binary),2)
    return int(binary, 2)
counters = [Counter(pos) for pos in transpose(content)]
gamma = ["0" if c["0"]>c["1"] else "1" for c in counters]
print(timeit.timeit(lambda:''.join(str(1-int(x)) for x in gamma)))
eps=''.join(str(1-int(x)) for x in gamma)
answ = bin2int(gamma) * bin2int(eps)
answ
#submit(answ, part="a", day=3, year=2021)


In [ ]:
gamma=4
print(timeit.timeit(lambda: (~gamma & 0xFFFFFF),number=100000))

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
def keep_criteria(diagnostics: tp.List[str],position:int,criteria:int) -> tp.List[str]:
    return list(filter(lambda x:x[position]==criteria,diagnostics))

ctr_position=0
oxygen=diagnostics
CO2=diagnostics

for position in range(len(diagnostics[0])):
    new_oxygen=keep_criteria(oxygen,position,most_common(oxygen,position))
    if len(new_oxygen)!=0:
        oxygen=new_oxygen
    new_CO2=keep_criteria(CO2,position,least_common(CO2,position))
    if len(new_CO2)!=0:
        CO2=new_CO2
    ctr_position+=1
oxygen=oxygen[0]
CO2=CO2[0]

ans_b=int(oxygen,2)*int(CO2,2)
print(ans_b)

In [ ]:
puzzle.answer_b = ans_b

### Day 2

In [15]:
puzzle=Puzzle(year=2021,day=2)
print(puzzle.easter_eggs)


[<span title="Tank, I need a pilot program for a B212 helicopter.">pilot this thing</span>]


#### Part a

In [ ]:
from abc import ABC,abstractmethod

class submarine(ABC):
    def __init__(self,depth=0,hor_pos=0):
        self.depth=depth
        self.hor_pos=hor_pos
    @abstractmethod
    def movement(self,direction:str, amount:int) -> None:
        raise notImplementedError(self.__class__.name+"movement")
    
    
class submarine_noob(submarine):
    
    def movement(self,direction, amount):
        if direction=="up":
            self.depth-=amount
        elif direction=="down":
            self.depth+=amount
        elif direction=="forward":
            self.hor_pos+=amount
        else:
            raise Exception("going in an unknown direction")


jack_sparrow=submarine_noob()
movements=puzzle.input_data.strip().split('\n')

for trajectory in movements:
    direction,amount=trajectory.split(' ')
    jack_sparrow.movement(direction,int(amount))

ans_a=jack_sparrow.depth*jack_sparrow.hor_pos

In [ ]:
puzzle.answer_a = ans_a
#submit(answer=ans_a,day=2,part="a",year=2021)

#### Part b

In [ ]:
class submarine_pro(submarine):

    def __init__(self,depth=0,hor_pos=0,aim=0):
        super().__init__(depth,hor_pos)
        self.aim=aim
    
    def movement(self,direction:str, amount:int):
        if direction=="up":
            self.aim-=amount
        elif direction=="down":
            self.aim+=amount
        elif direction=="forward":
            self.hor_pos+=amount
            self.depth+=self.aim*amount
        else:
            raise Exception("going in an unknown direction")

            
            
cousteau=submarine_pro()

movements=puzzle.input_data.strip().split('\n')

for trajectory in movements:
    direction,amount=trajectory.split(' ')
    cousteau.movement(direction,int(amount))

ans_b=cousteau.depth*cousteau.hor_pos

In [ ]:
puzzle.answer_b = ans_b

### Day 1

In [16]:
puzzle=Puzzle(year=2021,day=1)
print(puzzle.easter_eggs)


[<span title="Does this premise seem fishy to you?">carried into deeper water</span>]


In [ ]:
# depths=[int(dep) for dep in open("day1_input1.txt").read().strip().split('\n')]

depths=[int(dep) for dep in puzzle.input_data.strip().split('\n')]

def count_increase(depths: tp.Sequence[int],sliding_window: int) -> int:
    ctr_depth=0
    depth=sum(depths[:sliding_window])
    for i in range(len(depths)-sliding_window):
        if depths[i+sliding_window]>depths[i]:
            ctr_depth+=1
    return ctr_depth



In [ ]:
ans_a=count_increase(depths,1)
ans_b=count_increase(depths,3)

submit(answer=ans_a,day=1,part="a",year=2021)
submit(answer=ans_b,day=1,part="b",year=2021)
