# Advent of code 2021

In [ ]:
pip install aocd

In [1]:
### imports

from aocd import submit
from aocd.models import Puzzle
import typing as tp
import os
import numpy as np
import re

os.environ["AOC_SESSION"]="53616c7465645f5f6d9daabe7926fe3860734a70143382fbf0871c7206c1f5a9c1ed3158b28de5d90b71fc296387cb5b"

### Day 25

In [ ]:
puzzle=Puzzle(year=2021,day=25)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 24

In [ ]:
puzzle=Puzzle(year=2021,day=24)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 23

In [ ]:
puzzle=Puzzle(year=2021,day=23)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 22

In [ ]:
puzzle=Puzzle(year=2021,day=22)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 21

In [ ]:
puzzle=Puzzle(year=2021,day=21)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 20

In [ ]:
puzzle=Puzzle(year=2021,day=20)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 19

In [ ]:
puzzle=Puzzle(year=2021,day=19)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
submit(answer=ans_b,day=3,part="b",year=2021)

### Day 18

In [ ]:
puzzle=Puzzle(year=2021,day=18)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 17

In [ ]:
puzzle=Puzzle(year=2021,day=17)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 16

In [ ]:
puzzle=Puzzle(year=2021,day=16)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
submit(answer=ans_b,day=3,part="b",year=2021)

### Day 15

In [ ]:
puzzle=Puzzle(year=2021,day=15)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 14

In [ ]:
puzzle=Puzzle(year=2021,day=14)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 13

In [ ]:
puzzle=Puzzle(year=2021,day=13)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 12

In [ ]:
puzzle=Puzzle(year=2021,day=12)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 11

In [ ]:
puzzle=Puzzle(year=2021,day=11)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 10

In [ ]:
puzzle=Puzzle(year=2021,day=10)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 9

In [ ]:
puzzle=Puzzle(year=2021,day=9)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 8

In [ ]:
puzzle=Puzzle(year=2021,day=8)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 7

In [ ]:
puzzle=Puzzle(year=2021,day=7)

#### Part a

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
puzzle.answer_b = ans_b

### Day 6

In [2]:
puzzle=Puzzle(year=2021,day=6)

#### Part a

In [32]:
from collections import Counter

input_population=[int(val) for val in puzzle.input_data.split(",")]
#input_population=[int(val) for val in "3,4,3,1,2".split(',')]

fish=Counter(input_population)

def one_generation(fish_pop:Counter)->Counter:
    new_pop=fish_pop.copy()
    for age in range(8,0,-1):
        new_pop[age-1]=fish_pop[age]
    new_pop[6]+=fish_pop[0]
    new_pop[8]=fish_pop[0]
    return new_pop

target_a=80
for _ in range(target_a):
    fish=one_generation(fish)

print(fish)
ans_a=sum(fish.values())
print(ans_a)

Counter({6: 84247, 1: 63210, 3: 56666, 8: 52220, 4: 47533, 5: 39919, 2: 22914, 7: 15489, 0: 13429})
395627


In [30]:
puzzle.answer_a = ans_a

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


#### Part b

In [33]:
target_b=256
for _ in range(target_b-target_a):
    fish=one_generation(fish)

print(fish)
ans_b=sum(fish.values())
print(ans_b)

Counter({6: 298112625802, 4: 242275592950, 5: 224566658942, 3: 201537704873, 2: 188533531080, 1: 183896664441, 8: 162561758363, 0: 146348336343, 7: 119490666415})
1767323539209


In [34]:
puzzle.answer_b = ans_b

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 6! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


### Day 5

In [2]:
puzzle=Puzzle(year=2021,day=5)

#### Part a

In [3]:
winds=[line.split(" -> ") for line in puzzle.input_data.strip().split('\n')]

    
class Coordinate:
    def __init__(self,x:int,y:int) -> None:
        self.x=x
        self.y=y


        
class Wind:
    def __init__(self,start_point:Coordinate,end_point:Coordinate) -> None:
        self.start_point=start_point
        self.end_point=end_point
        
    def get_coords(self) -> tp.List[Coordinate]:
        n_points=max(abs(self.start_point.x-self.end_point.x),abs(self.start_point.y-self.end_point.y))
        for n in range(n_points+1):
            if abs((self.start_point.x+n*(self.end_point.x-self.start_point.x)/(n_points))%1)>0.0000001:
                print("shit)")
            if abs((self.start_point.y+n*(self.end_point.y-self.start_point.y)/(n_points))%1>0.0000001):
                print("shit 2")
        return [Coordinate(int(self.start_point.x+n*(self.end_point.x-self.start_point.x)/(n_points)),
                     int(self.start_point.y+n*(self.end_point.y-self.start_point.y)/(n_points))) for n in range(n_points+1)]

    def is_straight(self) -> bool:
        if self.start_point.x==self.end_point.x or self.start_point.y==self.end_point.y:
            return True
        else:
            #print("no",self.start_point.x-self.end_point.x,self.start_point.y-self.end_point.y)
            return False


#winds=[line.split(" -> ") for line in open("example_day5.txt").read().strip().split('\n')]
#print(len(winds))
        
winds=[Wind(Coordinate(int(line[0].split(',')[0]),int(line[0].split(',')[1])),Coordinate(int(line[1].split(',')[0]),int(line[1].split(',')[1]))) for line in winds]     

#print(winds[8].start_point.x,winds[8].start_point.y,winds[8].end_point.x,winds[8].end_point.y,winds[8].is_straight())

grid=np.zeros((max([max(wind.start_point.y,wind.end_point.y) for wind in winds])+1,max([max(wind.start_point.x,wind.end_point.x) for wind in winds])+1))

test_wind1=Wind(Coordinate(0,35),Coordinate(0,13))
#print(test_wind1.is_straight())
ctr=0
#for coord in test_wind1.get_coords():
    #print(coord.x,coord.y)
    #ctr+=1

total_sum=0
for wind in winds:
    if wind.is_straight():
        total_sum+=(abs(wind.start_point.x-wind.end_point.x)+abs(wind.start_point.y-wind.end_point.y)+1)
        ctr+=1
        for coord in wind.get_coords():
            grid[coord.y,coord.x]+=1
#    else:
#        np.set_printoptions(threshold=sys.maxsize)
#        print(np.nonzero(grid))
#        print(wind.start_point.x,wind.start_point.y)
#        asadasd
print(ctr)


print(grid)
#print(sum(sum(grid)),total_sum)
ans_a=len([val for val in grid.flatten() if val>1])
print(ans_a)
#def find_intersect(wind1:wind,wind2:wind) -> [bool,tp.List[coord]]:
    

339
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
5774


In [4]:
puzzle.answer_a = ans_a

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


#### Part b

In [9]:
ctr=0
grid=np.zeros((max([max(wind.start_point.y,wind.end_point.y) for wind in winds])+1,max([max(wind.start_point.x,wind.end_point.x) for wind in winds])+1))
for wind in winds:
    total_sum+=(abs(wind.start_point.x-wind.end_point.x)+abs(wind.start_point.y-wind.end_point.y)+1)
    ctr+=1
    for coord in wind.get_coords():
        grid[coord.y,coord.x]+=1
ans_b=len([val for val in grid.flatten() if val>1])
print(ans_b)


18423


In [10]:
puzzle.answer_b = ans_b

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 5! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


### Day 4

In [ ]:
puzzle=Puzzle(year=2021,day=4)

#### Part a

In [ ]:
input_data=puzzle.input_data.split('\n\n')

drawn_numbers=[int(number) for number in input_data[0].split(',')]
boards=input_data[1:]

class bingo_board:
    def __init__(self,list_of_numbers:str) -> None:
        self.board_numbers=np.array([[int(number) for number in line.strip().split()] for line in list_of_numbers.split('\n')])
    
    def check_row(self,id_row:int,list_of_numbers:tp.List[int]):
        if all([number in list_of_numbers for number in self.board_numbers[id_row,:]]):
            return True
        else:
            return False
    def check_col(self,id_col:int,list_of_numbers:tp.List[int]):
        self.board_numbers=np.transpose(self.board_numbers)
        return_value=self.check_row(id_col,list_of_numbers)
        self.board_numbers=np.transpose(self.board_numbers)
        return return_value
    
    def check_win(self,list_of_numbers:tp.List[int]):
        if any([self.check_col(idx,list_of_numbers) or self.check_row(idx,list_of_numbers) for idx in range(len(self.board_numbers))]):
            return True
        else:
            return False

boards=[bingo_board(board) for board in boards]

def play_game_well(bingo_boards:tp.List[bingo_board],drawn_numbers:tp.List[int]):
    for n_drawn in range(len(bingo_boards[0].board_numbers),len(drawn_numbers)):
        for board in bingo_boards:
            if(board.check_win(drawn_numbers[:n_drawn])):
                return [board,n_drawn]


[board,n_drawn]=play_game_well(boards,drawn_numbers)
score=sum([number for number in  board.board_numbers.flat if not number in drawn_numbers[:n_drawn]])*drawn_numbers[n_drawn-1]
ans_a=score
print(score)

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
def play_game_badly(bingo_boards:tp.List[bingo_board],drawn_numbers:tp.List[int]):
    worst_n_drawn=0
    for id_board,board in enumerate(bingo_boards):
        [bad_board,n_win]=play_game_well([board],drawn_numbers)
        if n_win>worst_n_drawn:
            worst_n_drawn=n_win
            worst_board=bad_board
    return [worst_board,worst_n_drawn]

[board,n_drawn]=play_game_badly(boards,drawn_numbers)
score=sum([number for number in  board.board_numbers.flat if not number in drawn_numbers[:n_drawn]])*drawn_numbers[n_drawn-1]
ans_b=score
print(score)

In [ ]:
puzzle.answer_b = ans_b

### Day 3

In [ ]:
puzzle=Puzzle(year=2021,day=3)

#### Part a

In [ ]:
import timeit

diagnostics=puzzle.input_data.strip().split('\n')

def most_common(diagnostics: tp.List[str],position:int) -> str:
    all_bits=[diag[position] for diag in diagnostics]
    return max(sorted(set(all_bits),reverse=True), key = all_bits.count)

def least_common(diagnostics: tp.List[str],position:int) -> str:
    return str(1-int(most_common(diagnostics,position)))

gamma=""
for position in range(len(diagnostics[0])):
    gamma+=most_common(diagnostics,position)

gamma=int(gamma,2)


print(timeit.timeit(lambda: 2**(len(diagnostics[0]))-1-gamma,number=100000))
epsilon=2**(len(diagnostics[0]))-1-gamma

ans_a=gamma*epsilon
print(ans_a)

#### Nao's solution for timeit

In [ ]:
from collections import Counter
content = puzzle.input_data.split("\n")
def transpose(inlist: tp.Sequence[str]) -> tp.List[str]: 
    return ["".join(s) for s in zip(*inlist)]
def bin2int(binary: tp.Union[str, tp.Sequence[str]]) -> int: 
    if isinstance(binary, list): 
        return int("".join(binary),2)
    return int(binary, 2)
counters = [Counter(pos) for pos in transpose(content)]
gamma = ["0" if c["0"]>c["1"] else "1" for c in counters]
print(timeit.timeit(lambda:''.join(str(1-int(x)) for x in gamma)))
eps=''.join(str(1-int(x)) for x in gamma)
answ = bin2int(gamma) * bin2int(eps)
answ
#submit(answ, part="a", day=3, year=2021)


In [ ]:
gamma=4
print(timeit.timeit(lambda: (~gamma & 0xFFFFFF),number=100000))

In [ ]:
puzzle.answer_a = ans_a

#### Part b

In [ ]:
def keep_criteria(diagnostics: tp.List[str],position:int,criteria:int) -> tp.List[str]:
    return list(filter(lambda x:x[position]==criteria,diagnostics))

ctr_position=0
oxygen=diagnostics
CO2=diagnostics

for position in range(len(diagnostics[0])):
    new_oxygen=keep_criteria(oxygen,position,most_common(oxygen,position))
    if len(new_oxygen)!=0:
        oxygen=new_oxygen
    new_CO2=keep_criteria(CO2,position,least_common(CO2,position))
    if len(new_CO2)!=0:
        CO2=new_CO2
    ctr_position+=1
oxygen=oxygen[0]
CO2=CO2[0]

ans_b=int(oxygen,2)*int(CO2,2)
print(ans_b)

In [ ]:
puzzle.answer_b = ans_b

### Day 2

In [ ]:
puzzle=Puzzle(year=2021,day=2)

#### Part a

In [ ]:
from abc import ABC,abstractmethod

class submarine(ABC):
    def __init__(self,depth=0,hor_pos=0):
        self.depth=depth
        self.hor_pos=hor_pos
    @abstractmethod
    def movement(self,direction:str, amount:int) -> None:
        raise notImplementedError(self.__class__.name+"movement")
    
    
class submarine_noob(submarine):
    
    def movement(self,direction, amount):
        if direction=="up":
            self.depth-=amount
        elif direction=="down":
            self.depth+=amount
        elif direction=="forward":
            self.hor_pos+=amount
        else:
            raise Exception("going in an unknown direction")


jack_sparrow=submarine_noob()
movements=puzzle.input_data.strip().split('\n')

for trajectory in movements:
    direction,amount=trajectory.split(' ')
    jack_sparrow.movement(direction,int(amount))

ans_a=jack_sparrow.depth*jack_sparrow.hor_pos

In [ ]:
puzzle.answer_a = ans_a
#submit(answer=ans_a,day=2,part="a",year=2021)

#### Part b

In [ ]:
class submarine_pro(submarine):

    def __init__(self,depth=0,hor_pos=0,aim=0):
        super().__init__(depth,hor_pos)
        self.aim=aim
    
    def movement(self,direction:str, amount:int):
        if direction=="up":
            self.aim-=amount
        elif direction=="down":
            self.aim+=amount
        elif direction=="forward":
            self.hor_pos+=amount
            self.depth+=self.aim*amount
        else:
            raise Exception("going in an unknown direction")

            
            
cousteau=submarine_pro()

movements=puzzle.input_data.strip().split('\n')

for trajectory in movements:
    direction,amount=trajectory.split(' ')
    cousteau.movement(direction,int(amount))

ans_b=cousteau.depth*cousteau.hor_pos

In [ ]:
puzzle.answer_b = ans_b

### Day 1

In [ ]:
puzzle=Puzzle(year=2021,day=1)

In [ ]:
# depths=[int(dep) for dep in open("day1_input1.txt").read().strip().split('\n')]

depths=[int(dep) for dep in puzzle.input_data.strip().split('\n')]

def count_increase(depths: tp.Sequence[int],sliding_window: int) -> int:
    ctr_depth=0
    depth=sum(depths[:sliding_window])
    for i in range(len(depths)-sliding_window):
        if depths[i+sliding_window]>depths[i]:
            ctr_depth+=1
    return ctr_depth



In [ ]:
ans_a=count_increase(depths,1)
ans_b=count_increase(depths,3)

submit(answer=ans_a,day=1,part="a",year=2021)
submit(answer=ans_b,day=1,part="b",year=2021)
